library(htmltools)
library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(bs4Dash)
library(markdown)
library(shinybusy)
library(shinythemes)
library(plotly)
library(fresh)
library(DT)
library(utils)
library(dplyr)
library(jsonlite)
library(httr)
library(enrichR)
library(RDAVIDWebService)
library(logging)
library(shinyjs)
library(ggplot2)
library(stringdist)
library(ggvenn)
library(VennDiagram)
library(tidyr)
#library(knitr)
library(purrr)
library(plotly)
library(igraph)
# word cloud
library(tm)
library(wordcloud)
library(SnowballC)
options(repos = BiocManager::repositories())

#if("AnnotationDbi" %in% rownames(installed.packages()) == FALSE)
#  BiocManager::install("AnnotationDbi")
library(AnnotationDbi)#